### ISSUE TITLE
Error starting connection to PyCharm

### ISSUE THREAD

**Issue by mholden8** [SlicerRt/SlicerDebuggingTools#6] opened 2017-07-21 14:48 UTC
When I try to connect to PyCharm from the latest nightly version of Slicer, I get the following error message when I click "Connect to debug server":

![image](https://user-images.githubusercontent.com/3238050/28468523-3ad68ff2-6e01-11e7-94c0-e7f89d922e6f.png)

Note that this error does not occur with older versions (e.g. Slicer 2017-06-26), where I can successfully connect.

OS: Windows 10
Slicer: Slicer 2017-07-20 (latest nightly)
PyCharm: 2017.1

Slicer log file attached.
[Slicer_26159_20170721_103713.txt](https://github.com/SlicerRt/SlicerDebuggingTools/files/1165851/Slicer_26159_20170721_103713.txt)

**Comment by lassoan** [comment] 2017-07-21 18:38
Thanks a lot for reporting, the problem is now fixed (it was a regression introduced 1-2 days ago when I added VisualStudio support). It'll be work again in tomorrow's nightly build or you can download and update PyDevRemoteDebug\PyDevRemoteDebug.py manually on your computer now.

Reopen this ticket if the problem still exists in tomorrow's nightly build.

**Closed by lassoan** 2017-07-21 18:38 UTC

**Comment by mholden8** [comment] 2017-07-24 13:06
Thank you @lassoan. It is working for me now.
